apiVersion: v1
kind: Service
metadata:
  name: node-jenkins-app-service
spec:
  type: NodePort
  selector:
    app: node-jenkins-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
